### ISSUE TITLE
replace mpi with pthread or cuda?

### ISSUE THREAD

**Issue by fengwang** [rahulsrma26/simpleNN#1]
Considering
+ a nvidia gpu sometimes can accelerate the performance by a factor of 100 with CUDA or 50 times with opencl;
+ [POSIX thread tends to give out better performance than MPI](https://ieeexplore.ieee.org/document/6544384)

is it possible to make an abstract backend engine implementing all the computational expensive operations using different frameworks  (MPI, pthread, opencl, CUDA), rather than explicitly hard-coded everything in the source files?

**Comment by rahulsrma26** [comment]
Thanks for the suggestion. Previously, I was thinking OpenCL because:
1. It can run on CPU, GPU and FPGA etc.
2. I've a prior development experience in it.

But it's support seems dead to me as both MacOS stopped supporting and Nvidia still supports only v1.2 in 2019. Also AMD is going towards ROCm side. Problem with CUDA is no one with AMD GPU can use it. So I'm confused between OpenCL and SYCL. I'll include some GPU support in next version.

I used OpenMP because of ease of use. Out of the box it is supported by many compilers. And performance hit is negligible these days (that paper was 2013 this is latest https://www.researchgate.net/publication/220105874_OpenMP_versus_threading_in_CC).

It will be my end goal to make an abstract backend. So that user can choose at the time of cmake.
The current goal of this library is to keep it simple so that the inner-workings can be understood. And using small datasets it's already quite fast on CPU (faster than tensorflow-cpu) tested on single hidden layer with 300 neurons with MNIST data.
